services:
  navidrome:
    image: deluan/navidrome:latest
    user: "${PUID}:${PGID}"
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # These variables control the internal Navidrome engine
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: "${NAVIDROME_BASE_URL}"
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
    volumes:
      # Mapping our /opt/stacks folders into the container
      - "${STACK_DIR}/data:/data"
      - "${MUSIC_FOLDER}:/music:ro"
