services:
  navidrome:
    image: deluan/navidrome:latest
    user: "${PUID}:${PGID}"
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: "${NAVIDROME_BASE_URL}"
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      # Optional: Use folder names as Album titles if tags are missing
      ND_ALBUMIDENTIFIER: folder
    volumes:
      - "${STACK_DIR}/data:/data"
      - "${MUSIC_FOLDER}:/music"

